package vista;
import controladores.CuentaControllerListas;
import javax.swing.*;
/*import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;*/

/**
 *
 * @author alexg
 */
public class FrmPrincipalAdministrador extends javax.swing.JFrame {

    private CuentaControllerListas cc = new CuentaControllerListas();
    
    /**
     * Creates new form FrmPrincipalAdministrador
     */
    public FrmPrincipalAdministrador(String nombre, String apellidos) {
        initComponents();
        this.setLocationRelativeTo(null);
        jblNombre.setText(nombre + " " + apellidos);
        cargarIconos();
        //System.out.println("Comentario prueba");
    }
    
    private void cargarIconos(){
        btncursa.setIcon(new ImageIcon("src\\icono\\cursa.png"));
        btncurso.setIcon(new ImageIcon("src\\icono\\curso.png"));
        btndocentes.setIcon(new ImageIcon("src\\icono\\docentes.png"));
        btnestudiantes.setIcon(new ImageIcon("src\\icono\\estudiantes.png"));
        btnmalla.setIcon(new ImageIcon("src\\icono\\malla.png"));
        btnmaterias.setIcon(new ImageIcon("src\\icono\\materias.png"));
        btnmatricula.setIcon(new ImageIcon("src\\icono\\matricula.png"));
        btnperiodo.setIcon(new ImageIcon("src\\icono\\periodoAcademico.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jblNombre = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnmaterias = new javax.swing.JButton();
        btnestudiantes = new javax.swing.JButton();
        btndocentes = new javax.swing.JButton();
        btnmatricula = new javax.swing.JButton();
        btnmalla = new javax.swing.JButton();
        btncurso = new javax.swing.JButton();
        btnperiodo = new javax.swing.JButton();
        btncursa = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "[Administrador]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));
        jPanel3.add(jLabel1);

        jblNombre.setFont(new java.awt.Font("Harlow Solid Italic", 1, 18)); // NOI18N
        jblNombre.setForeground(new java.awt.Color(0, 0, 153));
        jblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombre.setText("Administrador");
        jPanel3.add(jblNombre);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 430));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204), 5), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnmaterias.setBackground(new java.awt.Color(0, 153, 153));
        btnmaterias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmaterias.setForeground(new java.awt.Color(255, 255, 255));
        btnmaterias.setText(" Administar Materias");
        btnmaterias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmateriasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnmaterias, gridBagConstraints);

        btnestudiantes.setBackground(new java.awt.Color(0, 153, 153));
        btnestudiantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnestudiantes.setForeground(new java.awt.Color(255, 255, 255));
        btnestudiantes.setText("Administrar Estudiantes\n\n");
        btnestudiantes.setActionCommand(" Administrar Estudiantes  ");
        btnestudiantes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnestudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnestudiantesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnestudiantes, gridBagConstraints);

        btndocentes.setBackground(new java.awt.Color(0, 153, 153));
        btndocentes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndocentes.setForeground(new java.awt.Color(255, 255, 255));
        btndocentes.setText(" Administar Docentes");
        btndocentes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocentesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btndocentes, gridBagConstraints);

        btnmatricula.setBackground(new java.awt.Color(0, 153, 153));
        btnmatricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmatricula.setForeground(new java.awt.Color(255, 255, 255));
        btnmatricula.setText("Matriculas");
        btnmatricula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmatriculaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 190;
        gridBagConstraints.ipady = 10;
        jPanel5.add(btnmatricula, gridBagConstraints);

        btnmalla.setBackground(new java.awt.Color(0, 153, 153));
        btnmalla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmalla.setForeground(new java.awt.Color(255, 255, 255));
        btnmalla.setText(" Malla");
        btnmalla.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmallaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 190;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnmalla, gridBagConstraints);

        btncurso.setBackground(new java.awt.Color(0, 153, 153));
        btncurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncurso.setForeground(new java.awt.Color(255, 255, 255));
        btncurso.setText(" Curso");
        btncurso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncursoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 190;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btncurso, gridBagConstraints);

        btnperiodo.setBackground(new java.awt.Color(0, 153, 153));
        btnperiodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnperiodo.setForeground(new java.awt.Color(255, 255, 255));
        btnperiodo.setText(" Periodo Academico");
        btnperiodo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperiodoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnperiodo, gridBagConstraints);

        btncursa.setBackground(new java.awt.Color(0, 153, 153));
        btncursa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncursa.setForeground(new java.awt.Color(255, 255, 255));
        btncursa.setText("Cursa");
        btncursa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncursaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 190;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btncursa, gridBagConstraints);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 700, 410));

        jButton8.setBackground(new java.awt.Color(204, 255, 255));
        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmateriasActionPerformed
        new FrmMateria().setVisible(true);
    }//GEN-LAST:event_btnmateriasActionPerformed

    private void btncursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncursoActionPerformed
        new FrmCurso().setVisible(true);
    }//GEN-LAST:event_btncursoActionPerformed

    private void btnmallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmallaActionPerformed
        new FrmMalla().setVisible(true);
    }//GEN-LAST:event_btnmallaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new FrmIniciarSesion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnestudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnestudiantesActionPerformed
        new FrmEstudiante().setVisible(true);
    }//GEN-LAST:event_btnestudiantesActionPerformed

    private void btndocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocentesActionPerformed
        new FrmDocente().setVisible(true);
    }//GEN-LAST:event_btndocentesActionPerformed

    private void btnmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmatriculaActionPerformed
        new FrmMatricula().setVisible(true);
    }//GEN-LAST:event_btnmatriculaActionPerformed

    private void btnperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperiodoActionPerformed
        new FrmPeriodoAcademico().setVisible(true);
    }//GEN-LAST:event_btnperiodoActionPerformed

    private void btncursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncursaActionPerformed
     new FrmCursaAdmin().setVisible(true);
    }//GEN-LAST:event_btncursaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String nombres = null;
                String apellidos = null;
                new FrmPrincipalAdministrador(nombres, apellidos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncursa;
    private javax.swing.JButton btncurso;
    private javax.swing.JButton btndocentes;
    private javax.swing.JButton btnestudiantes;
    private javax.swing.JButton btnmalla;
    private javax.swing.JButton btnmaterias;
    private javax.swing.JButton btnmatricula;
    private javax.swing.JButton btnperiodo;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jblNombre;
    // End of variables declaration//GEN-END:variables
}
